### ISSUE TITLE
practica 1 boolena

### ISSUE THREAD

**Issue by AlynGomez12** [SistemasTecTlaxiaco/actividad-10-expresiones-boolenas-equipo-f4#1]
[Practica1.mds (1).pdf](https://github.com/user-attachments/files/18044562/Practica1.mds.1.pdf)

**Comment by Proyect-A16** [comment]
Portada:25/25
Procedimiento:25/25
Figuras, Ilustraciones y Fotografías:25/25
Resultados y conclusiones:25/25
Total:100/100

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
